server:
  port: 8040
spring:
  application:
    name: order-nacos-demo
  #配置nacos服务端
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
#feign日志全局配置
logging:
  level:
    com.spring.cloud.demo.order.feign: debug
feign:
  client:
    config:
      member-nacos-demo:
#        loggerLevel: HEADERS
        contract: feign.Contract.Default
        connecTimeout: 5000
        readTimeout: 4000
        requestInterceptors[0]:
          com.spring.cloud.demo.order.interceptor.FeignInterceptor
